import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { createContext } from 'react';
import CounterContextProvider from '../components/CounterContextProvider';
import CounterDisplay from '../components/CounterDisplay';
import IncrementBtn from '../components/IncrementBtn';
import DecrementBtn from '../components/DecrementBtn';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <h1>React Context Api</h1>
        <CounterContextProvider>
          <div>
            <CounterDisplay />
            <IncrementBtn />
            <DecrementBtn />
          </div>
        </CounterContextProvider>
      </main>
    </div>
  );
};

export default Home;
